### ISSUE TITLE
how to configure mongodb client storage?

### ISSUE THREAD

**Issue by melanger** [UniversitaDellaCalabria/SATOSA-oidcop#2]
I cannot make this work with mongodb used for clients (without any dynamic registrations). The problem manifests when doing e.g. basic auth (see https://github.com/IdentityPython/oidc-op/issues/141)

If I use this config (from the ["working" example](https://github.com/italia/Satosa-Saml2Spid/blob/master/example/plugins/frontends/oidc_op_frontend.yaml)):

```
config:
    storage:
        class: "satosa_oidcop.core.storage.mongo.Mongodb"
        kwargs:
            url: mongodb://satosa-mongo:27017/oidcop
            connection_params:
                username: satosa
                password: thatpassword
        db_name: oidcop
        collections:
            # type: collection name
            session: session
            client: client
```

Everything works except basic auth. At some point, SATOSA logs:

```
No special client db, will use memory based dictionary
```

`cdb` used inside client_authn.py is empty and basic auth fails, because client secrets cannot be compared.

When I try to add `client_db` configuration, like this:

```
config:
    storage:
        class: "satosa_oidcop.core.storage.mongo.Mongodb"
        kwargs:
            url: mongodb://satosa-mongo:27017/oidcop
            connection_params:
                username: satosa
                password: thatpassword
        db_name: oidcop
        collections:
            # type: collection name
            session: session
            client: client
    op:
        server_info:
            client_db:
                class: "satosa_oidcop.core.storage.mongo.Mongodb"
                kwargs:
                      storage_conf:
                          db_name: oidcop
                          collections:
                              session: session
                              client: client
                      url: mongodb://satosa-mongo:27017/oidcop
                      connection_params:
                          username: satosa
                          password: thatpassword
```

it fails again, with a slightly different message:

```
Verifying auth using client_secret_basic failed: 'Mongodb' object is not subscriptable
```

which is probably thrown from here:

https://github.com/IdentityPython/oidc-op/blob/66eb57b305258308365b5439bb1f41c32950018b/src/oidcop/client_authn.py#L108

I believe I need a different `class` under `client_db`.

**Comment by peppelinux** [comment]
Hi @melanger 

you have only use the main config.storage here, without the client_db
https://github.com/italia/Satosa-Saml2Spid/blob/840af6f60217bb7449d396f3da38d09a548ee9ad/example/plugins/frontends/oidc_op_frontend.yaml#L9

as you can see you already have in it

````
        db_name: oidcop
        collections:
            # type: collection name
            session: session
            client: client
````

Feel free to close this issue when you're done
