### ISSUE TITLE
example satosa config doesn't work

### ISSUE THREAD

**Issue by MdreW** [UniversitaDellaCalabria/SATOSA-oidcop#57]
At start satosa stop work with this error:
```
capabilities does not seems to be a valid configuration parameter
```
I Think that is referred to this configuration line
https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/abd97fdb8e201668a10cb3cce8db82e3e0f96aae/example/oidcop_frontend.yaml#L57
```
      capabilities:
        grant_types_supported:
          - authorization_code
          - urn:ietf:params:oauth:grant-type:jwt-bearer
          - refresh_token
        subject_types_supported:
          - public
          - pairwise
        scopes_supported:
          - openid
          - profile
          - offline_access
        claims_supported:
          - sub
          - given_name
          - birthdate
          - email
```
